### PR TITLE
update settings

### PR DESCRIPTION
**Pull request by nsoch**
Trying something different as I don't have the right link to use your nkg repository

### CODE REVIEW

**Comment by nsoch** [comment]
well what it did is just go to the link for this website which is confusing to me. will try a different tactic

**Comment by vsoch** [comment]
It's a modular strategy so you don't put everything in one repo. This is also why you develop locally so you don't publish a broken site...

I'm going to move this repo over to you (transfer) so it's completely under your control. Please accept the email when you get it.

**Comment by nsoch** [comment]
Okie

**Comment by nsoch** [comment]
The link did not work for NKG. Will try to delete branch but not sure how to do it. Will do it now

**Pull request merged**
