### PR TITLE
update projects

### PR DESCRIPTION
**Pull request by nsoch**
working on this today as I need to make it happen whatever way is easier for me. I have not uploaded the images yet so it will not be visually correct

### CODE REVIEW

**Comment by vsoch** [comment]
This is your site, so your power to do as you like! If there is a build error Github will send you an email message, and the (old) site won't be updated.

**Comment by nsoch** [comment]
I changed the colors for the wild dreamer but when i look at the site the colors are the same even if i reload so what am I missing?

**Comment by vsoch** [comment]
They are changed. The page is cached  in your browser. Open up development console and click the setting to not use the cache when devtools is open.

**Comment by nsoch** [comment]
Never mind the colors did change, YAHOOOEEY!

**Pull request merged**
